lang: # ex. ru
pointer:
  style: '>> '
achivements:
  mamont: true
langlist:
  - id: ru
    name: Russian
  - id: en
    name: English
commands:
  - start
  - help
  - dialog
  - new
  - news
  - echo
  - rand
  - about
images:
  dino: |
    ░▄▄▄▄░
    ▀▀▄██►
    ▀▀███►
    ░▀███►░█►
    ▒▄████▀▀
  snail: |
    ───▄▄▄
    ─▄▀░▄░▀▄
    ─█░█▄▀░█
    ─█░▀▄▄▀█▄█▄▀
    ▄▄█▄▄▄▄███▀
