name: Build exe, create release

on:
  push:
    branches: main

  workflow_dispatch:

jobs:
  build_x64:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Run PyInstaller
        run: |
          python -m PyInstaller pbot.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: PBot.exe
          path: dist/pbot.exe

      - name: Create release draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.head_commit.message }}
          release_name: ${{ github.event.head_commit.message }}
          overwrite: true
          body: |
            ## [What's new?][News] [![Badge (Release)]](https://github.com/TRFish/PBot/releases/latest)
            - Updated the list of commands
            - Added restart function
            - Added "About PBot" feature
            - Questions?

            [News]: https://github.com/TRFish/PBot/blob/main/news.md
            [Badge (Release)]: https://img.shields.io/github/v/release/TRFish/PBot

          draft: true
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: dist/pbot.exe
          asset_name: PBot.exe
          asset_content_type: application/zip
